name: Dev deploy
on:
  push:
    branches:
      - beta
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: '22.x'
    - name: Build
      run: |
        npm ci
        npm run build
      env:
        CI_MODE: dev
    - name: Pack
      run: |
        npm run package
      env:
        CI_MODE: dev
    - name: Deploy
      uses: trmcnvn/chrome-addon@7fc5a5ad3ff597dc64d6a13de7dcaa8515328be7 # v2
      with:
        extension: neekhcfkcjbddejgenpcdnpnidnfdgoh
        zip: dist/webextension.zip
        client-id: ${{ secrets.DEV_CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.DEV_CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.DEV_CHROME_REFRESH_TOKEN }}
